version: "3"
services:
  apollo-server:
    command: "npm run start"
    build:
      context: .
    image: node:lts
    environment:
      - EXPO_PUBLIC_FIREBASE_API_KEY=${EXPO_PUBLIC_FIREBASE_API_KEY}
      - EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN=${EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - EXPO_PUBLIC_FIREBASE_PROJECT_ID=${EXPO_PUBLIC_FIREBASE_PROJECT_ID}
      - EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET=${EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET}
      - EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - EXPO_PUBLIC_FIREBASE_APP_ID=${EXPO_PUBLIC_FIREBASE_APP_ID}
      - EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID=${EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID}
      - EXPO_PUBLIC_APOLLO_CLIENT_SERVER_URL=${EXPO_PUBLIC_APOLLO_CLIENT_SERVER_URL}
      - EXPO_PUBLIC_API_KEY=${EXPO_PUBLIC_API_KEY}
    ports:
      - 8081:8081
    volumes:
      - .:/code
      - ./package.json:/code/package.json
      - ./package-lock.json:/code/package-lock.json
    env_file:
      - .env
volumes:
